// TESTEO DE RUTAS DE PRODUCTO

GET http://localhost:8080/api/productos

###
GET http://localhost:8080/api/productos/2

###
POST http://localhost:8080/api/productos

### 
POST http://localhost:8080/api/productos
Content-Type: application/json

{
    "name":"Remera", "description":"Remera de los beatles", "code":"R001", "thumbnail":"https://backendbase.com/i/p/beatles-abbey-road-walk-white-t-shirt-f31b3.jpg", "price":"30", "stock":17
} 

###
PUT http://localhost:8080/api/productos/4
Content-Type: application/json

{
    "name":"Remera", "description":"Remera de los Beatles", "code":"R004", "thumbnail":"https://backendbase.com/i/p/beatles-abbey-road-walk-white-t-shirt-f31b3.jpg", "price":"30", "stock":17
} 
###
DELETE http://localhost:8080/api/productos/4


// TESTEO DE RUTAS DE CARRITO
###
POST http://localhost:8080/api/carrito
Content-Type: application/json

{
    "data": "Julian"
}

###
DELETE http://localhost:8080/api/carrito/idCarrito

###
GET http://localhost:8080/api/carrito/idCarrito/productos

###
POST http://localhost:8080/api/carrito/idCarrito/productos

###
DELETE http://localhost:8080/api/carrito/idCarrito/productos/idProducto

// TESTEO DE RUTAS NO IMPLEMENTADAS
###
GET http://localhost:8080/noimplementada
###
POST http://localhost:8080/noimplementada
###
PUT http://localhost:8080/noimplementada
###
DELETE  http://localhost:8080/noimplementada